version:  "3.0"

services:
  cssserver:
   image: infracloudio/csvserver:latest
   ports:
     - "9393:9300"
   environment:
     - CSVSERVER_BORDER=Orange
   volumes:
     - type: bind
       source: C:\Users\Bhavani_Vemuri\source\csvserver\solution\inputfile
       target: /csvserver/inputdata